options:
  copy: false

dev:
  files:
    '<%= dev %>/js/sea-userStatic-config.js': '<%= helper %>/sea-config.json'

pre-dist:
  options:
    mapping: '<%= temp %>/mapping.json'
    reload:
      - transport
  files:
    '<%= temp %>/sea-config.json': '<%= helper %>/sea-config.json'

dist:
  files:
    '<%= dist %>/js/sea-userStatic-config.js': '<%= temp %>/sea-config.json'